// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package frontend

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"max-width: 700px;margin-left: auto; margin-right: auto;\"><p>War Thunder Heatmaps is a small project aimed at revival of now defunct WT-Heatmaps project made by <a href=\"https://github.com/Sgambe33\">Sgambe33</a>. Everything you see on this website was made possible with <a href=\"https://github.com/maxsupermanhd/wrpl-inspector\">wrpl-inspector</a> and very helpful community members. Currently thunder.nanachi.party operates in close cooperation with <a href=\"https://wtapi.dev/\">Spectra WTApi</a> project.</p><p>Any help is appreciated, feel free to reach out with your suggestions/ideas. At the moment everything is powered by Golang and PostgreSQL. Currently database stores player kills (as per kill log in-game, with position attached). It allows for a lot of data rendering options and I am open for suggestions and contributions. If you are web developer (primarily frontend: styling, very light plain js and htmx tech) feel free to improve the website with your contributions. There are many TODOs that I am underqualified or too lazy to do.</p><p>If you want to use images or data generated/stored by the website feel free to contact me to get API or database access. API access is completely free with no strings attached. If you want something custom (either rendering or various data aggregates/views) it can be added.</p><p>You can contact me via:<ul><li><a href=\"https://discord.gg/2dTx8GdTj5\">Discord</a> (@flexcoral ID 343418440423309314)</li><li>Telegram @flexcoral</li><li>Discussions or issues on GitHub repositories of wrpl-inspector or wt-heatmaps</li><li>contact@nanachi.party</li></ul></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
