// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: replay.proto

package luxprotogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wrapper every serialized replay travels in. Frozen: identical in every schema version,
// so the version and body kind can always be read before the body is decoded.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Schema version the body was written with.
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                         // Body message type: "full" (Replay) | "light" (LightReplay).
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                         // Serialized body of that version, of the type named by kind.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Envelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// The replay header.
type LightReplay struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // Replay identifier, unique per battle.
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // Battle type: sqb | tss | random.
	MissionMode string                 `protobuf:"bytes,3,opt,name=mission_mode,json=missionMode,proto3" json:"mission_mode,omitempty"` // Game mode, e.g. Domination.
	MissionName string                 `protobuf:"bytes,4,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"` // Map name, e.g. Vietnam.
	StartTs     uint32                 `protobuf:"varint,5,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`            // Battle start, unix seconds.
	EndTs       uint32                 `protobuf:"varint,6,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`                  // Battle end, unix seconds.
	Duration    uint32                 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`                         // Seconds played.
	LevelPath   string                 `protobuf:"bytes,8,opt,name=level_path,json=levelPath,proto3" json:"level_path,omitempty"`       // Map file path.
	MissionPath string                 `protobuf:"bytes,9,opt,name=mission_path,json=missionPath,proto3" json:"mission_path,omitempty"` // Mission file path.
	Difficulty  string                 `protobuf:"bytes,10,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                     // arcade | realistic | hardcore.
	Cluster     string                 `protobuf:"bytes,11,opt,name=cluster,proto3" json:"cluster,omitempty"`                           // Server cluster: CIS | EU | NA | SA.
	Draw        bool                   `protobuf:"varint,12,opt,name=draw,proto3" json:"draw,omitempty"`                                // True when the battle ended in a draw.
	WinnerTeam  uint32                 `protobuf:"varint,13,opt,name=winner_team,json=winnerTeam,proto3" json:"winner_team,omitempty"`  // Winning team number, 1 or 2. Zero on a draw.
	LoserTeam   uint32                 `protobuf:"varint,14,opt,name=loser_team,json=loserTeam,proto3" json:"loser_team,omitempty"`     // Losing team number, 1 or 2. Zero on a draw.
	// Squadron tags of the two teams. Present only in squadron battles, where a team is
	// one squadron; in other modes every player carries their own tag instead. On a draw,
	// team 1's tag is in winner_tag and team 2's in loser_tag.
	WinnerTag *string    `protobuf:"bytes,15,opt,name=winner_tag,json=winnerTag,proto3,oneof" json:"winner_tag,omitempty"`
	LoserTag  *string    `protobuf:"bytes,16,opt,name=loser_tag,json=loserTag,proto3,oneof" json:"loser_tag,omitempty"`
	ClanElo   []*ClanElo `protobuf:"bytes,17,rep,name=clan_elo,json=clanElo,proto3" json:"clan_elo,omitempty"` // Squadron points for the battle, one entry per squadron.
	// Processing metadata.
	Status        string    `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`   // pending | in_progress | completed | failed.
	Ttp           uint32    `protobuf:"varint,19,opt,name=ttp,proto3" json:"ttp,omitempty"`        // Seconds spent processing.
	Delay         int32     `protobuf:"varint,20,opt,name=delay,proto3" json:"delay,omitempty"`    // Seconds between the battle ending and it being processed.
	Detail        string    `protobuf:"bytes,21,opt,name=detail,proto3" json:"detail,omitempty"`   // Failure reason: "Downloading error" | "Parsing error". failed only.
	Tss           *Tss      `protobuf:"bytes,22,opt,name=tss,proto3" json:"tss,omitempty"`         // Tournament data. tss battles only.
	Players       []*Player `protobuf:"bytes,23,rep,name=players,proto3" json:"players,omitempty"` // Scoreboard, one entry per player.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightReplay) Reset() {
	*x = LightReplay{}
	mi := &file_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightReplay) ProtoMessage() {}

func (x *LightReplay) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightReplay.ProtoReflect.Descriptor instead.
func (*LightReplay) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{1}
}

func (x *LightReplay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LightReplay) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LightReplay) GetMissionMode() string {
	if x != nil {
		return x.MissionMode
	}
	return ""
}

func (x *LightReplay) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

func (x *LightReplay) GetStartTs() uint32 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *LightReplay) GetEndTs() uint32 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *LightReplay) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *LightReplay) GetLevelPath() string {
	if x != nil {
		return x.LevelPath
	}
	return ""
}

func (x *LightReplay) GetMissionPath() string {
	if x != nil {
		return x.MissionPath
	}
	return ""
}

func (x *LightReplay) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *LightReplay) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *LightReplay) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

func (x *LightReplay) GetWinnerTeam() uint32 {
	if x != nil {
		return x.WinnerTeam
	}
	return 0
}

func (x *LightReplay) GetLoserTeam() uint32 {
	if x != nil {
		return x.LoserTeam
	}
	return 0
}

func (x *LightReplay) GetWinnerTag() string {
	if x != nil && x.WinnerTag != nil {
		return *x.WinnerTag
	}
	return ""
}

func (x *LightReplay) GetLoserTag() string {
	if x != nil && x.LoserTag != nil {
		return *x.LoserTag
	}
	return ""
}

func (x *LightReplay) GetClanElo() []*ClanElo {
	if x != nil {
		return x.ClanElo
	}
	return nil
}

func (x *LightReplay) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LightReplay) GetTtp() uint32 {
	if x != nil {
		return x.Ttp
	}
	return 0
}

func (x *LightReplay) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *LightReplay) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *LightReplay) GetTss() *Tss {
	if x != nil {
		return x.Tss
	}
	return nil
}

func (x *LightReplay) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// One battle in full: the header plus every heavy section.
type Replay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Light         *LightReplay           `protobuf:"bytes,1,opt,name=light,proto3" json:"light,omitempty"`                        // The header.
	PosQuant      uint32                 `protobuf:"varint,2,opt,name=pos_quant,json=posQuant,proto3" json:"pos_quant,omitempty"` // Divisor for every position channel: value / pos_quant = metres.
	AngQuant      uint32                 `protobuf:"varint,3,opt,name=ang_quant,json=angQuant,proto3" json:"ang_quant,omitempty"` // Divisor for every angle channel: value / ang_quant = radians.
	Chat          []*ChatLine            `protobuf:"bytes,4,rep,name=chat,proto3" json:"chat,omitempty"`                          // Chat messages, in order.
	Kills         []*Kill                `protobuf:"bytes,5,rep,name=kills,proto3" json:"kills,omitempty"`
	Damage        []*Damage              `protobuf:"bytes,6,rep,name=damage,proto3" json:"damage,omitempty"`
	Awards        []*Award               `protobuf:"bytes,7,rep,name=awards,proto3" json:"awards,omitempty"`
	Interceptions []*Interception        `protobuf:"bytes,8,rep,name=interceptions,proto3" json:"interceptions,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,9,rep,name=entities,proto3" json:"entities,omitempty"`        // Unit trajectories, one entry per spawned vehicle.
	Projectiles   []*Projectile          `protobuf:"bytes,10,rep,name=projectiles,proto3" json:"projectiles,omitempty"` // Bomb and rocket trajectories.
	Zones         []*Zone                `protobuf:"bytes,11,rep,name=zones,proto3" json:"zones,omitempty"`             // Capture zones.
	Tickets       *Tickets               `protobuf:"bytes,12,opt,name=tickets,proto3" json:"tickets,omitempty"`         // Ticket history of both teams.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replay) Reset() {
	*x = Replay{}
	mi := &file_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{2}
}

func (x *Replay) GetLight() *LightReplay {
	if x != nil {
		return x.Light
	}
	return nil
}

func (x *Replay) GetPosQuant() uint32 {
	if x != nil {
		return x.PosQuant
	}
	return 0
}

func (x *Replay) GetAngQuant() uint32 {
	if x != nil {
		return x.AngQuant
	}
	return 0
}

func (x *Replay) GetChat() []*ChatLine {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *Replay) GetKills() []*Kill {
	if x != nil {
		return x.Kills
	}
	return nil
}

func (x *Replay) GetDamage() []*Damage {
	if x != nil {
		return x.Damage
	}
	return nil
}

func (x *Replay) GetAwards() []*Award {
	if x != nil {
		return x.Awards
	}
	return nil
}

func (x *Replay) GetInterceptions() []*Interception {
	if x != nil {
		return x.Interceptions
	}
	return nil
}

func (x *Replay) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Replay) GetProjectiles() []*Projectile {
	if x != nil {
		return x.Projectiles
	}
	return nil
}

func (x *Replay) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *Replay) GetTickets() *Tickets {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type Tss struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TournamentId   uint32                 `protobuf:"varint,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	TournamentName string                 `protobuf:"bytes,2,opt,name=tournament_name,json=tournamentName,proto3" json:"tournament_name,omitempty"`
	MatchId        string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Bracket        string                 `protobuf:"bytes,4,opt,name=bracket,proto3" json:"bracket,omitempty"` // Bracket type, e.g. swiss.
	Team1          *TssTeam               `protobuf:"bytes,5,opt,name=team1,proto3" json:"team1,omitempty"`     // First team of the match.
	Team2          *TssTeam               `protobuf:"bytes,6,opt,name=team2,proto3" json:"team2,omitempty"`     // Second team of the match.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tss) Reset() {
	*x = Tss{}
	mi := &file_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tss) ProtoMessage() {}

func (x *Tss) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tss.ProtoReflect.Descriptor instead.
func (*Tss) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{3}
}

func (x *Tss) GetTournamentId() uint32 {
	if x != nil {
		return x.TournamentId
	}
	return 0
}

func (x *Tss) GetTournamentName() string {
	if x != nil {
		return x.TournamentName
	}
	return ""
}

func (x *Tss) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Tss) GetBracket() string {
	if x != nil {
		return x.Bracket
	}
	return ""
}

func (x *Tss) GetTeam1() *TssTeam {
	if x != nil {
		return x.Team1
	}
	return nil
}

func (x *Tss) GetTeam2() *TssTeam {
	if x != nil {
		return x.Team2
	}
	return nil
}

type TssTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName      string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	CaptainId     string                 `protobuf:"bytes,3,opt,name=captain_id,json=captainId,proto3" json:"captain_id,omitempty"` // uid of the team captain.
	Players       []*TssPlayer           `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`                      // Team roster.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TssTeam) Reset() {
	*x = TssTeam{}
	mi := &file_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TssTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TssTeam) ProtoMessage() {}

func (x *TssTeam) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TssTeam.ProtoReflect.Descriptor instead.
func (*TssTeam) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{4}
}

func (x *TssTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TssTeam) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TssTeam) GetCaptainId() string {
	if x != nil {
		return x.CaptainId
	}
	return ""
}

func (x *TssTeam) GetPlayers() []*TssPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type TssPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // Role in the team.
	PvpRatio      string                 `protobuf:"bytes,3,opt,name=pvp_ratio,json=pvpRatio,proto3" json:"pvp_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TssPlayer) Reset() {
	*x = TssPlayer{}
	mi := &file_replay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TssPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TssPlayer) ProtoMessage() {}

func (x *TssPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TssPlayer.ProtoReflect.Descriptor instead.
func (*TssPlayer) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{5}
}

func (x *TssPlayer) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TssPlayer) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TssPlayer) GetPvpRatio() string {
	if x != nil {
		return x.PvpRatio
	}
	return ""
}

type Player struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Pid                uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`        // Row index in the scoreboard.
	Uid                string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`         // War Thunder user id.
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`       // Player nickname.
	Tag                string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`         // Squadron tag; the team number when unknown in a squadron battle.
	Team               uint32                 `protobuf:"varint,5,opt,name=team,proto3" json:"team,omitempty"`      // Team number, 1 or 2.
	Country            string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"` // Nation the player fought for, e.g. usa.
	AirKills           uint32                 `protobuf:"varint,7,opt,name=air_kills,json=airKills,proto3" json:"air_kills,omitempty"`
	GroundKills        uint32                 `protobuf:"varint,8,opt,name=ground_kills,json=groundKills,proto3" json:"ground_kills,omitempty"`
	Assists            uint32                 `protobuf:"varint,9,opt,name=assists,proto3" json:"assists,omitempty"`
	Deaths             uint32                 `protobuf:"varint,10,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Captures           uint32                 `protobuf:"varint,11,opt,name=captures,proto3" json:"captures,omitempty"` // Zones captured.
	Score              uint32                 `protobuf:"varint,12,opt,name=score,proto3" json:"score,omitempty"`
	MissileEvades      uint32                 `protobuf:"varint,13,opt,name=missile_evades,json=missileEvades,proto3" json:"missile_evades,omitempty"`
	ShellInterceptions uint32                 `protobuf:"varint,14,opt,name=shell_interceptions,json=shellInterceptions,proto3" json:"shell_interceptions,omitempty"`
	TeamKills          uint32                 `protobuf:"varint,15,opt,name=team_kills,json=teamKills,proto3" json:"team_kills,omitempty"`
	Units              []*Unit                `protobuf:"bytes,16,rep,name=units,proto3" json:"units,omitempty"`   // Vehicles available to the player in this battle.
	Elo                *Elo                   `protobuf:"bytes,17,opt,name=elo,proto3,oneof" json:"elo,omitempty"` // Rating before and after. Squadron battles only, absent when not computed.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_replay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{6}
}

func (x *Player) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Player) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Player) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *Player) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Player) GetAirKills() uint32 {
	if x != nil {
		return x.AirKills
	}
	return 0
}

func (x *Player) GetGroundKills() uint32 {
	if x != nil {
		return x.GroundKills
	}
	return 0
}

func (x *Player) GetAssists() uint32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *Player) GetDeaths() uint32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *Player) GetCaptures() uint32 {
	if x != nil {
		return x.Captures
	}
	return 0
}

func (x *Player) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetMissileEvades() uint32 {
	if x != nil {
		return x.MissileEvades
	}
	return 0
}

func (x *Player) GetShellInterceptions() uint32 {
	if x != nil {
		return x.ShellInterceptions
	}
	return 0
}

func (x *Player) GetTeamKills() uint32 {
	if x != nil {
		return x.TeamKills
	}
	return 0
}

func (x *Player) GetUnits() []*Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *Player) GetElo() *Elo {
	if x != nil {
		return x.Elo
	}
	return nil
}

type Elo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // Rating before the battle.
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // Rating after the battle.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Elo) Reset() {
	*x = Elo{}
	mi := &file_replay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Elo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elo) ProtoMessage() {}

func (x *Elo) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elo.ProtoReflect.Descriptor instead.
func (*Elo) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{7}
}

func (x *Elo) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Elo) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type ClanElo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`        // Full squadron tag, brackets included.
	Start         int32                  `protobuf:"zigzag32,2,opt,name=start,proto3" json:"start,omitempty"` // Squadron points before the battle. Signed: a total can be negative.
	End           int32                  `protobuf:"zigzag32,3,opt,name=end,proto3" json:"end,omitempty"`     // Squadron points after the battle. Signed: a total can be negative.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClanElo) Reset() {
	*x = ClanElo{}
	mi := &file_replay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClanElo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClanElo) ProtoMessage() {}

func (x *ClanElo) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClanElo.ProtoReflect.Descriptor instead.
func (*ClanElo) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{8}
}

func (x *ClanElo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ClanElo) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ClanElo) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

// One vehicle in a player's lineup.
type Unit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Used          bool                   `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`                                 // True when the player spawned in this vehicle.
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                // Internal in-game id, e.g. us_m1_abrams.
	UnitName      string                 `protobuf:"bytes,3,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`          // Display name; falls back to unit_id when untranslated.
	UnitType      string                 `protobuf:"bytes,4,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`          // tank | aircraft | helicopter | ship | ...
	UnitClass     string                 `protobuf:"bytes,5,opt,name=unit_class,json=unitClass,proto3" json:"unit_class,omitempty"`       // Vehicle class, e.g. medium tank, fighter.
	UnitCountry   string                 `protobuf:"bytes,6,opt,name=unit_country,json=unitCountry,proto3" json:"unit_country,omitempty"` // Country of origin, e.g. usa.
	Free          *bool                  `protobuf:"varint,7,opt,name=free,proto3,oneof" json:"free,omitempty"`                           // Vehicle granted on top of the lineup. Random battles only.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unit) Reset() {
	*x = Unit{}
	mi := &file_replay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{9}
}

func (x *Unit) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *Unit) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Unit) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *Unit) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *Unit) GetUnitClass() string {
	if x != nil {
		return x.UnitClass
	}
	return ""
}

func (x *Unit) GetUnitCountry() string {
	if x != nil {
		return x.UnitCountry
	}
	return ""
}

func (x *Unit) GetFree() bool {
	if x != nil && x.Free != nil {
		return *x.Free
	}
	return false
}

// Trajectory of one spawned vehicle, on three independent time axes: t for the
// hull, view_t for the camera, turret_t for gun aiming.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                        // Owner player uid, "0" when none.
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                    // Internal in-game id; ground vehicles carry the tankModels/ prefix.
	T             []int32                `protobuf:"zigzag32,3,rep,packed,name=t,proto3" json:"t,omitempty"`                                  // Time deltas of the hull channels, ms.
	X             []int32                `protobuf:"zigzag32,4,rep,packed,name=x,proto3" json:"x,omitempty"`                                  // X deltas.
	Y             []int32                `protobuf:"zigzag32,5,rep,packed,name=y,proto3" json:"y,omitempty"`                                  // Y deltas. Y is altitude.
	Z             []int32                `protobuf:"zigzag32,6,rep,packed,name=z,proto3" json:"z,omitempty"`                                  // Z deltas.
	HullYaw       []int32                `protobuf:"zigzag32,7,rep,packed,name=hull_yaw,json=hullYaw,proto3" json:"hull_yaw,omitempty"`       // Hull yaw deltas, on the t axis.
	HullPitch     []int32                `protobuf:"zigzag32,8,rep,packed,name=hull_pitch,json=hullPitch,proto3" json:"hull_pitch,omitempty"` // Hull pitch deltas, on the t axis.
	HullRoll      []int32                `protobuf:"zigzag32,9,rep,packed,name=hull_roll,json=hullRoll,proto3" json:"hull_roll,omitempty"`    // Hull roll deltas, on the t axis.
	ViewT         []int32                `protobuf:"zigzag32,10,rep,packed,name=view_t,json=viewT,proto3" json:"view_t,omitempty"`            // Time deltas of the camera channels, ms. Empty when the replay has no camera data.
	CamYaw        []int32                `protobuf:"zigzag32,11,rep,packed,name=cam_yaw,json=camYaw,proto3" json:"cam_yaw,omitempty"`         // Camera yaw deltas, on the view_t axis. Within +-pi.
	CamPitch      []int32                `protobuf:"zigzag32,12,rep,packed,name=cam_pitch,json=camPitch,proto3" json:"cam_pitch,omitempty"`   // Camera pitch deltas, on the view_t axis.
	CamRoll       []int32                `protobuf:"zigzag32,13,rep,packed,name=cam_roll,json=camRoll,proto3" json:"cam_roll,omitempty"`      // Camera roll deltas, on the view_t axis. Within +-pi/2.
	AimYaw        []int32                `protobuf:"zigzag32,14,rep,packed,name=aim_yaw,json=aimYaw,proto3" json:"aim_yaw,omitempty"`         // Yaw of the aiming reticle, on the view_t axis. Where the guns are told to converge, not where they are.
	AimPitch      []int32                `protobuf:"zigzag32,15,rep,packed,name=aim_pitch,json=aimPitch,proto3" json:"aim_pitch,omitempty"`   // Pitch of the aiming reticle, on the view_t axis.
	TurretT       []int32                `protobuf:"zigzag32,16,rep,packed,name=turret_t,json=turretT,proto3" json:"turret_t,omitempty"`      // Time deltas of the gun aiming channels, ms. Shared by every gun of this vehicle.
	Weapons       []*Weapon              `protobuf:"bytes,17,rep,name=weapons,proto3" json:"weapons,omitempty"`                               // Aiming angles, one entry per gun. Ground vehicles only.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_replay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{10}
}

func (x *Entity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Entity) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Entity) GetT() []int32 {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Entity) GetX() []int32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Entity) GetY() []int32 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *Entity) GetZ() []int32 {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *Entity) GetHullYaw() []int32 {
	if x != nil {
		return x.HullYaw
	}
	return nil
}

func (x *Entity) GetHullPitch() []int32 {
	if x != nil {
		return x.HullPitch
	}
	return nil
}

func (x *Entity) GetHullRoll() []int32 {
	if x != nil {
		return x.HullRoll
	}
	return nil
}

func (x *Entity) GetViewT() []int32 {
	if x != nil {
		return x.ViewT
	}
	return nil
}

func (x *Entity) GetCamYaw() []int32 {
	if x != nil {
		return x.CamYaw
	}
	return nil
}

func (x *Entity) GetCamPitch() []int32 {
	if x != nil {
		return x.CamPitch
	}
	return nil
}

func (x *Entity) GetCamRoll() []int32 {
	if x != nil {
		return x.CamRoll
	}
	return nil
}

func (x *Entity) GetAimYaw() []int32 {
	if x != nil {
		return x.AimYaw
	}
	return nil
}

func (x *Entity) GetAimPitch() []int32 {
	if x != nil {
		return x.AimPitch
	}
	return nil
}

func (x *Entity) GetTurretT() []int32 {
	if x != nil {
		return x.TurretT
	}
	return nil
}

func (x *Entity) GetWeapons() []*Weapon {
	if x != nil {
		return x.Weapons
	}
	return nil
}

// Aiming angles of one gun, on the turret_t axis of the owning entity. Angles are
// world frame, in the same convention as hull_*: turret rotation relative to the
// hull is turret_yaw - hull_yaw, gun elevation relative to the turret is
// gun_pitch - turret_pitch.
type Weapon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model bone the barrel fires from, e.g. bone_gun_barrel | bone_mg_aa_v_01.
	// Unique within a vehicle: two records with the same gun_id differ only by this.
	Mount         string  `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	GunId         string  `protobuf:"bytes,2,opt,name=gun_id,json=gunId,proto3" json:"gun_id,omitempty"`                             // Internal in-game id of the barrel or launcher.
	GunName       string  `protobuf:"bytes,3,opt,name=gun_name,json=gunName,proto3" json:"gun_name,omitempty"`                       // Display name; falls back to gun_id when untranslated.
	TurretYaw     []int32 `protobuf:"zigzag32,4,rep,packed,name=turret_yaw,json=turretYaw,proto3" json:"turret_yaw,omitempty"`       // Turret heading deltas.
	TurretPitch   []int32 `protobuf:"zigzag32,5,rep,packed,name=turret_pitch,json=turretPitch,proto3" json:"turret_pitch,omitempty"` // Turret pitch deltas.
	GunPitch      []int32 `protobuf:"zigzag32,6,rep,packed,name=gun_pitch,json=gunPitch,proto3" json:"gun_pitch,omitempty"`          // Gun elevation deltas.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_replay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{11}
}

func (x *Weapon) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Weapon) GetGunId() string {
	if x != nil {
		return x.GunId
	}
	return ""
}

func (x *Weapon) GetGunName() string {
	if x != nil {
		return x.GunName
	}
	return ""
}

func (x *Weapon) GetTurretYaw() []int32 {
	if x != nil {
		return x.TurretYaw
	}
	return nil
}

func (x *Weapon) GetTurretPitch() []int32 {
	if x != nil {
		return x.TurretPitch
	}
	return nil
}

func (x *Weapon) GetGunPitch() []int32 {
	if x != nil {
		return x.GunPitch
	}
	return nil
}

// Flight path of one bomb or rocket.
type Projectile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                 // Owner player uid, "0" when unknown.
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`             // Internal id of the vehicle it was fired from.
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                               // bomb | rocket | ...
	WeaponId      string                 `protobuf:"bytes,4,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`       // Internal in-game id of the munition, e.g. fr_ss_11.
	WeaponName    string                 `protobuf:"bytes,5,opt,name=weapon_name,json=weaponName,proto3" json:"weapon_name,omitempty"` // Short display name, e.g. AIM-9B; falls back to weapon_id.
	T             []int32                `protobuf:"zigzag32,6,rep,packed,name=t,proto3" json:"t,omitempty"`                           // Time deltas, ms.
	X             []int32                `protobuf:"zigzag32,7,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y             []int32                `protobuf:"zigzag32,8,rep,packed,name=y,proto3" json:"y,omitempty"` // Y is altitude.
	Z             []int32                `protobuf:"zigzag32,9,rep,packed,name=z,proto3" json:"z,omitempty"`
	Yaw           []int32                `protobuf:"zigzag32,10,rep,packed,name=yaw,proto3" json:"yaw,omitempty"` // Projectile yaw deltas, on the t axis.
	Pitch         []int32                `protobuf:"zigzag32,11,rep,packed,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          []int32                `protobuf:"zigzag32,12,rep,packed,name=roll,proto3" json:"roll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projectile) Reset() {
	*x = Projectile{}
	mi := &file_replay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projectile) ProtoMessage() {}

func (x *Projectile) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projectile.ProtoReflect.Descriptor instead.
func (*Projectile) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{12}
}

func (x *Projectile) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Projectile) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Projectile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Projectile) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

func (x *Projectile) GetWeaponName() string {
	if x != nil {
		return x.WeaponName
	}
	return ""
}

func (x *Projectile) GetT() []int32 {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Projectile) GetX() []int32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Projectile) GetY() []int32 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *Projectile) GetZ() []int32 {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *Projectile) GetYaw() []int32 {
	if x != nil {
		return x.Yaw
	}
	return nil
}

func (x *Projectile) GetPitch() []int32 {
	if x != nil {
		return x.Pitch
	}
	return nil
}

func (x *Projectile) GetRoll() []int32 {
	if x != nil {
		return x.Roll
	}
	return nil
}

type Kill struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OffenderUid    string                 `protobuf:"bytes,1,opt,name=offender_uid,json=offenderUid,proto3" json:"offender_uid,omitempty"`            // Killer uid, "0" when crashed.
	OffenderUnitId string                 `protobuf:"bytes,2,opt,name=offender_unit_id,json=offenderUnitId,proto3" json:"offender_unit_id,omitempty"` // Killer vehicle id, empty when crashed.
	OffenderPos    []int32                `protobuf:"zigzag32,3,rep,packed,name=offender_pos,json=offenderPos,proto3" json:"offender_pos,omitempty"`  // Killer position (x, y, z), metres * pos_quant. Absolute, not delta encoded.
	// Munition id: a shell id for guns (152mm_xm578e1), a missile id for missiles
	// (fr_ss_11). Two special values: artillery for an artillery strike, and an
	// empty string for a ram.
	UsedWeaponId   string  `protobuf:"bytes,4,opt,name=used_weapon_id,json=usedWeaponId,proto3" json:"used_weapon_id,omitempty"`
	OffendedUid    string  `protobuf:"bytes,5,opt,name=offended_uid,json=offendedUid,proto3" json:"offended_uid,omitempty"`            // Victim uid.
	OffendedUnitId string  `protobuf:"bytes,6,opt,name=offended_unit_id,json=offendedUnitId,proto3" json:"offended_unit_id,omitempty"` // Victim vehicle id.
	OffendedPos    []int32 `protobuf:"zigzag32,7,rep,packed,name=offended_pos,json=offendedPos,proto3" json:"offended_pos,omitempty"`  // Victim position (x, y, z), metres * pos_quant.
	Crashed        bool    `protobuf:"varint,8,opt,name=crashed,proto3" json:"crashed,omitempty"`                                      // True when the victim died with no opponent involved.
	Time           uint32  `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`                                            // Battle time, ms.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Kill) Reset() {
	*x = Kill{}
	mi := &file_replay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kill) ProtoMessage() {}

func (x *Kill) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kill.ProtoReflect.Descriptor instead.
func (*Kill) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{13}
}

func (x *Kill) GetOffenderUid() string {
	if x != nil {
		return x.OffenderUid
	}
	return ""
}

func (x *Kill) GetOffenderUnitId() string {
	if x != nil {
		return x.OffenderUnitId
	}
	return ""
}

func (x *Kill) GetOffenderPos() []int32 {
	if x != nil {
		return x.OffenderPos
	}
	return nil
}

func (x *Kill) GetUsedWeaponId() string {
	if x != nil {
		return x.UsedWeaponId
	}
	return ""
}

func (x *Kill) GetOffendedUid() string {
	if x != nil {
		return x.OffendedUid
	}
	return ""
}

func (x *Kill) GetOffendedUnitId() string {
	if x != nil {
		return x.OffendedUnitId
	}
	return ""
}

func (x *Kill) GetOffendedPos() []int32 {
	if x != nil {
		return x.OffendedPos
	}
	return nil
}

func (x *Kill) GetCrashed() bool {
	if x != nil {
		return x.Crashed
	}
	return false
}

func (x *Kill) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Damage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OffenderUid    string                 `protobuf:"bytes,1,opt,name=offender_uid,json=offenderUid,proto3" json:"offender_uid,omitempty"`            // Damage dealer uid, "0" when unknown.
	OffenderUnitId string                 `protobuf:"bytes,2,opt,name=offender_unit_id,json=offenderUnitId,proto3" json:"offender_unit_id,omitempty"` // Damage dealer vehicle id. Often empty even when offender_uid is known.
	OffendedUid    string                 `protobuf:"bytes,3,opt,name=offended_uid,json=offendedUid,proto3" json:"offended_uid,omitempty"`            // Damaged player uid.
	OffendedUnitId string                 `protobuf:"bytes,4,opt,name=offended_unit_id,json=offendedUnitId,proto3" json:"offended_unit_id,omitempty"` // Damaged vehicle id.
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                             // severe | critical | ...
	Afire          *bool                  `protobuf:"varint,6,opt,name=afire,proto3,oneof" json:"afire,omitempty"`                                    // Target set on fire. Critical damage only.
	Time           uint32                 `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`                                            // Battle time, ms.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Damage) Reset() {
	*x = Damage{}
	mi := &file_replay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{14}
}

func (x *Damage) GetOffenderUid() string {
	if x != nil {
		return x.OffenderUid
	}
	return ""
}

func (x *Damage) GetOffenderUnitId() string {
	if x != nil {
		return x.OffenderUnitId
	}
	return ""
}

func (x *Damage) GetOffendedUid() string {
	if x != nil {
		return x.OffendedUid
	}
	return ""
}

func (x *Damage) GetOffendedUnitId() string {
	if x != nil {
		return x.OffendedUnitId
	}
	return ""
}

func (x *Damage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Damage) GetAfire() bool {
	if x != nil && x.Afire != nil {
		return *x.Afire
	}
	return false
}

func (x *Damage) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Award struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`     // Awarded player uid.
	Award         string                 `protobuf:"bytes,2,opt,name=award,proto3" json:"award,omitempty"` // Award identifier, e.g. first_blood.
	Time          uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`  // Battle time, ms.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Award) Reset() {
	*x = Award{}
	mi := &file_replay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Award) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Award) ProtoMessage() {}

func (x *Award) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Award.ProtoReflect.Descriptor instead.
func (*Award) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{15}
}

func (x *Award) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Award) GetAward() string {
	if x != nil {
		return x.Award
	}
	return ""
}

func (x *Award) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// A munition shot down in flight. The victim is the munition, not a vehicle.
type Interception struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OffenderUid         string                 `protobuf:"bytes,1,opt,name=offender_uid,json=offenderUid,proto3" json:"offender_uid,omitempty"`                           // Interceptor uid, "0" when unknown.
	OffenderUnitId      string                 `protobuf:"bytes,2,opt,name=offender_unit_id,json=offenderUnitId,proto3" json:"offender_unit_id,omitempty"`                // Interceptor vehicle id.
	OffendedUid         string                 `protobuf:"bytes,3,opt,name=offended_uid,json=offendedUid,proto3" json:"offended_uid,omitempty"`                           // Uid of the player whose munition was destroyed.
	UsedWeaponId        string                 `protobuf:"bytes,4,opt,name=used_weapon_id,json=usedWeaponId,proto3" json:"used_weapon_id,omitempty"`                      // Munition used to intercept.
	InterceptedWeaponId string                 `protobuf:"bytes,5,opt,name=intercepted_weapon_id,json=interceptedWeaponId,proto3" json:"intercepted_weapon_id,omitempty"` // Munition that was destroyed.
	Time                uint32                 `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`                                                           // Battle time, ms.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Interception) Reset() {
	*x = Interception{}
	mi := &file_replay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interception) ProtoMessage() {}

func (x *Interception) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interception.ProtoReflect.Descriptor instead.
func (*Interception) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{16}
}

func (x *Interception) GetOffenderUid() string {
	if x != nil {
		return x.OffenderUid
	}
	return ""
}

func (x *Interception) GetOffenderUnitId() string {
	if x != nil {
		return x.OffenderUnitId
	}
	return ""
}

func (x *Interception) GetOffendedUid() string {
	if x != nil {
		return x.OffendedUid
	}
	return ""
}

func (x *Interception) GetUsedWeaponId() string {
	if x != nil {
		return x.UsedWeaponId
	}
	return ""
}

func (x *Interception) GetInterceptedWeaponId() string {
	if x != nil {
		return x.InterceptedWeaponId
	}
	return ""
}

func (x *Interception) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ChatLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`         // Sender uid, "0" when unknown.
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // all | team | ...
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Message text.
	Time          uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`      // Battle time, ms.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatLine) Reset() {
	*x = ChatLine{}
	mi := &file_replay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatLine) ProtoMessage() {}

func (x *ChatLine) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatLine.ProtoReflect.Descriptor instead.
func (*ChatLine) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{17}
}

func (x *ChatLine) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChatLine) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatLine) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`                     // Zone letter: A, B, C...
	IconIdx       uint32                 `protobuf:"varint,2,opt,name=icon_idx,json=iconIdx,proto3" json:"icon_idx,omitempty"` // Raw icon index the label is derived from.
	Center        []float32              `protobuf:"fixed32,3,rep,packed,name=center,proto3" json:"center,omitempty"`          // Zone center (x, y, z), metres, not quantized.
	Radius        float32                `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`                 // Zone radius, metres.
	CapT          []int32                `protobuf:"zigzag32,5,rep,packed,name=cap_t,json=capT,proto3" json:"cap_t,omitempty"` // Time deltas of the capture history, ms.
	CapV          []int32                `protobuf:"zigzag32,6,rep,packed,name=cap_v,json=capV,proto3" json:"cap_v,omitempty"` // Capture value deltas: -100 team 1, 0 neutral, 100 team 2.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_replay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{18}
}

func (x *Zone) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Zone) GetIconIdx() uint32 {
	if x != nil {
		return x.IconIdx
	}
	return 0
}

func (x *Zone) GetCenter() []float32 {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Zone) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Zone) GetCapT() []int32 {
	if x != nil {
		return x.CapT
	}
	return nil
}

func (x *Zone) GetCapV() []int32 {
	if x != nil {
		return x.CapV
	}
	return nil
}

type Tickets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team1T        []int32                `protobuf:"zigzag32,1,rep,packed,name=team1_t,json=team1T,proto3" json:"team1_t,omitempty"` // Time deltas of the team 1 ticket history, ms.
	Team1V        []int32                `protobuf:"zigzag32,2,rep,packed,name=team1_v,json=team1V,proto3" json:"team1_v,omitempty"` // Ticket value deltas for team 1.
	Team2T        []int32                `protobuf:"zigzag32,3,rep,packed,name=team2_t,json=team2T,proto3" json:"team2_t,omitempty"` // Time deltas of the team 2 ticket history, ms.
	Team2V        []int32                `protobuf:"zigzag32,4,rep,packed,name=team2_v,json=team2V,proto3" json:"team2_v,omitempty"` // Ticket value deltas for team 2.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tickets) Reset() {
	*x = Tickets{}
	mi := &file_replay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tickets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tickets) ProtoMessage() {}

func (x *Tickets) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tickets.ProtoReflect.Descriptor instead.
func (*Tickets) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{19}
}

func (x *Tickets) GetTeam1T() []int32 {
	if x != nil {
		return x.Team1T
	}
	return nil
}

func (x *Tickets) GetTeam1V() []int32 {
	if x != nil {
		return x.Team1V
	}
	return nil
}

func (x *Tickets) GetTeam2T() []int32 {
	if x != nil {
		return x.Team2T
	}
	return nil
}

func (x *Tickets) GetTeam2V() []int32 {
	if x != nil {
		return x.Team2V
	}
	return nil
}

var File_replay_proto protoreflect.FileDescriptor

const file_replay_proto_rawDesc = "" +
	"\n" +
	"\freplay.proto\x12\x05wt.v1\"Y\n" +
	"\bEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"\xc2\x05\n" +
	"\vLightReplay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fmission_mode\x18\x03 \x01(\tR\vmissionMode\x12!\n" +
	"\fmission_name\x18\x04 \x01(\tR\vmissionName\x12\x19\n" +
	"\bstart_ts\x18\x05 \x01(\rR\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x06 \x01(\rR\x05endTs\x12\x1a\n" +
	"\bduration\x18\a \x01(\rR\bduration\x12\x1d\n" +
	"\n" +
	"level_path\x18\b \x01(\tR\tlevelPath\x12!\n" +
	"\fmission_path\x18\t \x01(\tR\vmissionPath\x12\x1e\n" +
	"\n" +
	"difficulty\x18\n" +
	" \x01(\tR\n" +
	"difficulty\x12\x18\n" +
	"\acluster\x18\v \x01(\tR\acluster\x12\x12\n" +
	"\x04draw\x18\f \x01(\bR\x04draw\x12\x1f\n" +
	"\vwinner_team\x18\r \x01(\rR\n" +
	"winnerTeam\x12\x1d\n" +
	"\n" +
	"loser_team\x18\x0e \x01(\rR\tloserTeam\x12\"\n" +
	"\n" +
	"winner_tag\x18\x0f \x01(\tH\x00R\twinnerTag\x88\x01\x01\x12 \n" +
	"\tloser_tag\x18\x10 \x01(\tH\x01R\bloserTag\x88\x01\x01\x12)\n" +
	"\bclan_elo\x18\x11 \x03(\v2\x0e.wt.v1.ClanEloR\aclanElo\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12\x10\n" +
	"\x03ttp\x18\x13 \x01(\rR\x03ttp\x12\x14\n" +
	"\x05delay\x18\x14 \x01(\x05R\x05delay\x12\x16\n" +
	"\x06detail\x18\x15 \x01(\tR\x06detail\x12\x1c\n" +
	"\x03tss\x18\x16 \x01(\v2\n" +
	".wt.v1.TssR\x03tss\x12'\n" +
	"\aplayers\x18\x17 \x03(\v2\r.wt.v1.PlayerR\aplayersB\r\n" +
	"\v_winner_tagB\f\n" +
	"\n" +
	"_loser_tag\"\xe9\x03\n" +
	"\x06Replay\x12(\n" +
	"\x05light\x18\x01 \x01(\v2\x12.wt.v1.LightReplayR\x05light\x12\x1b\n" +
	"\tpos_quant\x18\x02 \x01(\rR\bposQuant\x12\x1b\n" +
	"\tang_quant\x18\x03 \x01(\rR\bangQuant\x12#\n" +
	"\x04chat\x18\x04 \x03(\v2\x0f.wt.v1.ChatLineR\x04chat\x12!\n" +
	"\x05kills\x18\x05 \x03(\v2\v.wt.v1.KillR\x05kills\x12%\n" +
	"\x06damage\x18\x06 \x03(\v2\r.wt.v1.DamageR\x06damage\x12$\n" +
	"\x06awards\x18\a \x03(\v2\f.wt.v1.AwardR\x06awards\x129\n" +
	"\rinterceptions\x18\b \x03(\v2\x13.wt.v1.InterceptionR\rinterceptions\x12)\n" +
	"\bentities\x18\t \x03(\v2\r.wt.v1.EntityR\bentities\x123\n" +
	"\vprojectiles\x18\n" +
	" \x03(\v2\x11.wt.v1.ProjectileR\vprojectiles\x12!\n" +
	"\x05zones\x18\v \x03(\v2\v.wt.v1.ZoneR\x05zones\x12(\n" +
	"\atickets\x18\f \x01(\v2\x0e.wt.v1.TicketsR\atickets\"\xd4\x01\n" +
	"\x03Tss\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\rR\ftournamentId\x12'\n" +
	"\x0ftournament_name\x18\x02 \x01(\tR\x0etournamentName\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12\x18\n" +
	"\abracket\x18\x04 \x01(\tR\abracket\x12$\n" +
	"\x05team1\x18\x05 \x01(\v2\x0e.wt.v1.TssTeamR\x05team1\x12$\n" +
	"\x05team2\x18\x06 \x01(\v2\x0e.wt.v1.TssTeamR\x05team2\"\x8a\x01\n" +
	"\aTssTeam\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12\x1d\n" +
	"\n" +
	"captain_id\x18\x03 \x01(\tR\tcaptainId\x12*\n" +
	"\aplayers\x18\x04 \x03(\v2\x10.wt.v1.TssPlayerR\aplayers\"N\n" +
	"\tTssPlayer\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1b\n" +
	"\tpvp_ratio\x18\x03 \x01(\tR\bpvpRatio\"\xe9\x03\n" +
	"\x06Player\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x12\n" +
	"\x04team\x18\x05 \x01(\rR\x04team\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1b\n" +
	"\tair_kills\x18\a \x01(\rR\bairKills\x12!\n" +
	"\fground_kills\x18\b \x01(\rR\vgroundKills\x12\x18\n" +
	"\aassists\x18\t \x01(\rR\aassists\x12\x16\n" +
	"\x06deaths\x18\n" +
	" \x01(\rR\x06deaths\x12\x1a\n" +
	"\bcaptures\x18\v \x01(\rR\bcaptures\x12\x14\n" +
	"\x05score\x18\f \x01(\rR\x05score\x12%\n" +
	"\x0emissile_evades\x18\r \x01(\rR\rmissileEvades\x12/\n" +
	"\x13shell_interceptions\x18\x0e \x01(\rR\x12shellInterceptions\x12\x1d\n" +
	"\n" +
	"team_kills\x18\x0f \x01(\rR\tteamKills\x12!\n" +
	"\x05units\x18\x10 \x03(\v2\v.wt.v1.UnitR\x05units\x12!\n" +
	"\x03elo\x18\x11 \x01(\v2\n" +
	".wt.v1.EloH\x00R\x03elo\x88\x01\x01B\x06\n" +
	"\x04_elo\"-\n" +
	"\x03Elo\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"C\n" +
	"\aClanElo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x11R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x11R\x03end\"\xd1\x01\n" +
	"\x04Unit\x12\x12\n" +
	"\x04used\x18\x01 \x01(\bR\x04used\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12\x1b\n" +
	"\tunit_name\x18\x03 \x01(\tR\bunitName\x12\x1b\n" +
	"\tunit_type\x18\x04 \x01(\tR\bunitType\x12\x1d\n" +
	"\n" +
	"unit_class\x18\x05 \x01(\tR\tunitClass\x12!\n" +
	"\funit_country\x18\x06 \x01(\tR\vunitCountry\x12\x17\n" +
	"\x04free\x18\a \x01(\bH\x00R\x04free\x88\x01\x01B\a\n" +
	"\x05_free\"\xa4\x03\n" +
	"\x06Entity\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12\f\n" +
	"\x01t\x18\x03 \x03(\x11R\x01t\x12\f\n" +
	"\x01x\x18\x04 \x03(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x03(\x11R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x03(\x11R\x01z\x12\x19\n" +
	"\bhull_yaw\x18\a \x03(\x11R\ahullYaw\x12\x1d\n" +
	"\n" +
	"hull_pitch\x18\b \x03(\x11R\thullPitch\x12\x1b\n" +
	"\thull_roll\x18\t \x03(\x11R\bhullRoll\x12\x15\n" +
	"\x06view_t\x18\n" +
	" \x03(\x11R\x05viewT\x12\x17\n" +
	"\acam_yaw\x18\v \x03(\x11R\x06camYaw\x12\x1b\n" +
	"\tcam_pitch\x18\f \x03(\x11R\bcamPitch\x12\x19\n" +
	"\bcam_roll\x18\r \x03(\x11R\acamRoll\x12\x17\n" +
	"\aaim_yaw\x18\x0e \x03(\x11R\x06aimYaw\x12\x1b\n" +
	"\taim_pitch\x18\x0f \x03(\x11R\baimPitch\x12\x19\n" +
	"\bturret_t\x18\x10 \x03(\x11R\aturretT\x12'\n" +
	"\aweapons\x18\x11 \x03(\v2\r.wt.v1.WeaponR\aweapons\"\xaf\x01\n" +
	"\x06Weapon\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x15\n" +
	"\x06gun_id\x18\x02 \x01(\tR\x05gunId\x12\x19\n" +
	"\bgun_name\x18\x03 \x01(\tR\agunName\x12\x1d\n" +
	"\n" +
	"turret_yaw\x18\x04 \x03(\x11R\tturretYaw\x12!\n" +
	"\fturret_pitch\x18\x05 \x03(\x11R\vturretPitch\x12\x1b\n" +
	"\tgun_pitch\x18\x06 \x03(\x11R\bgunPitch\"\xfd\x01\n" +
	"\n" +
	"Projectile\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tweapon_id\x18\x04 \x01(\tR\bweaponId\x12\x1f\n" +
	"\vweapon_name\x18\x05 \x01(\tR\n" +
	"weaponName\x12\f\n" +
	"\x01t\x18\x06 \x03(\x11R\x01t\x12\f\n" +
	"\x01x\x18\a \x03(\x11R\x01x\x12\f\n" +
	"\x01y\x18\b \x03(\x11R\x01y\x12\f\n" +
	"\x01z\x18\t \x03(\x11R\x01z\x12\x10\n" +
	"\x03yaw\x18\n" +
	" \x03(\x11R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\v \x03(\x11R\x05pitch\x12\x12\n" +
	"\x04roll\x18\f \x03(\x11R\x04roll\"\xba\x02\n" +
	"\x04Kill\x12!\n" +
	"\foffender_uid\x18\x01 \x01(\tR\voffenderUid\x12(\n" +
	"\x10offender_unit_id\x18\x02 \x01(\tR\x0eoffenderUnitId\x12!\n" +
	"\foffender_pos\x18\x03 \x03(\x11R\voffenderPos\x12$\n" +
	"\x0eused_weapon_id\x18\x04 \x01(\tR\fusedWeaponId\x12!\n" +
	"\foffended_uid\x18\x05 \x01(\tR\voffendedUid\x12(\n" +
	"\x10offended_unit_id\x18\x06 \x01(\tR\x0eoffendedUnitId\x12!\n" +
	"\foffended_pos\x18\a \x03(\x11R\voffendedPos\x12\x18\n" +
	"\acrashed\x18\b \x01(\bR\acrashed\x12\x12\n" +
	"\x04time\x18\t \x01(\rR\x04time\"\xef\x01\n" +
	"\x06Damage\x12!\n" +
	"\foffender_uid\x18\x01 \x01(\tR\voffenderUid\x12(\n" +
	"\x10offender_unit_id\x18\x02 \x01(\tR\x0eoffenderUnitId\x12!\n" +
	"\foffended_uid\x18\x03 \x01(\tR\voffendedUid\x12(\n" +
	"\x10offended_unit_id\x18\x04 \x01(\tR\x0eoffendedUnitId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x19\n" +
	"\x05afire\x18\x06 \x01(\bH\x00R\x05afire\x88\x01\x01\x12\x12\n" +
	"\x04time\x18\a \x01(\rR\x04timeB\b\n" +
	"\x06_afire\"C\n" +
	"\x05Award\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05award\x18\x02 \x01(\tR\x05award\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\"\xec\x01\n" +
	"\fInterception\x12!\n" +
	"\foffender_uid\x18\x01 \x01(\tR\voffenderUid\x12(\n" +
	"\x10offender_unit_id\x18\x02 \x01(\tR\x0eoffenderUnitId\x12!\n" +
	"\foffended_uid\x18\x03 \x01(\tR\voffendedUid\x12$\n" +
	"\x0eused_weapon_id\x18\x04 \x01(\tR\fusedWeaponId\x122\n" +
	"\x15intercepted_weapon_id\x18\x05 \x01(\tR\x13interceptedWeaponId\x12\x12\n" +
	"\x04time\x18\x06 \x01(\rR\x04time\"^\n" +
	"\bChatLine\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\"\x91\x01\n" +
	"\x04Zone\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x19\n" +
	"\bicon_idx\x18\x02 \x01(\rR\aiconIdx\x12\x16\n" +
	"\x06center\x18\x03 \x03(\x02R\x06center\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x02R\x06radius\x12\x13\n" +
	"\x05cap_t\x18\x05 \x03(\x11R\x04capT\x12\x13\n" +
	"\x05cap_v\x18\x06 \x03(\x11R\x04capV\"m\n" +
	"\aTickets\x12\x17\n" +
	"\ateam1_t\x18\x01 \x03(\x11R\x06team1T\x12\x17\n" +
	"\ateam1_v\x18\x02 \x03(\x11R\x06team1V\x12\x17\n" +
	"\ateam2_t\x18\x03 \x03(\x11R\x06team2T\x12\x17\n" +
	"\ateam2_v\x18\x04 \x03(\x11R\x06team2VB\x0fZ\r./luxprotogenb\x06proto3"

var (
	file_replay_proto_rawDescOnce sync.Once
	file_replay_proto_rawDescData []byte
)

func file_replay_proto_rawDescGZIP() []byte {
	file_replay_proto_rawDescOnce.Do(func() {
		file_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)))
	})
	return file_replay_proto_rawDescData
}

var file_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_replay_proto_goTypes = []any{
	(*Envelope)(nil),     // 0: wt.v1.Envelope
	(*LightReplay)(nil),  // 1: wt.v1.LightReplay
	(*Replay)(nil),       // 2: wt.v1.Replay
	(*Tss)(nil),          // 3: wt.v1.Tss
	(*TssTeam)(nil),      // 4: wt.v1.TssTeam
	(*TssPlayer)(nil),    // 5: wt.v1.TssPlayer
	(*Player)(nil),       // 6: wt.v1.Player
	(*Elo)(nil),          // 7: wt.v1.Elo
	(*ClanElo)(nil),      // 8: wt.v1.ClanElo
	(*Unit)(nil),         // 9: wt.v1.Unit
	(*Entity)(nil),       // 10: wt.v1.Entity
	(*Weapon)(nil),       // 11: wt.v1.Weapon
	(*Projectile)(nil),   // 12: wt.v1.Projectile
	(*Kill)(nil),         // 13: wt.v1.Kill
	(*Damage)(nil),       // 14: wt.v1.Damage
	(*Award)(nil),        // 15: wt.v1.Award
	(*Interception)(nil), // 16: wt.v1.Interception
	(*ChatLine)(nil),     // 17: wt.v1.ChatLine
	(*Zone)(nil),         // 18: wt.v1.Zone
	(*Tickets)(nil),      // 19: wt.v1.Tickets
}
var file_replay_proto_depIdxs = []int32{
	8,  // 0: wt.v1.LightReplay.clan_elo:type_name -> wt.v1.ClanElo
	3,  // 1: wt.v1.LightReplay.tss:type_name -> wt.v1.Tss
	6,  // 2: wt.v1.LightReplay.players:type_name -> wt.v1.Player
	1,  // 3: wt.v1.Replay.light:type_name -> wt.v1.LightReplay
	17, // 4: wt.v1.Replay.chat:type_name -> wt.v1.ChatLine
	13, // 5: wt.v1.Replay.kills:type_name -> wt.v1.Kill
	14, // 6: wt.v1.Replay.damage:type_name -> wt.v1.Damage
	15, // 7: wt.v1.Replay.awards:type_name -> wt.v1.Award
	16, // 8: wt.v1.Replay.interceptions:type_name -> wt.v1.Interception
	10, // 9: wt.v1.Replay.entities:type_name -> wt.v1.Entity
	12, // 10: wt.v1.Replay.projectiles:type_name -> wt.v1.Projectile
	18, // 11: wt.v1.Replay.zones:type_name -> wt.v1.Zone
	19, // 12: wt.v1.Replay.tickets:type_name -> wt.v1.Tickets
	4,  // 13: wt.v1.Tss.team1:type_name -> wt.v1.TssTeam
	4,  // 14: wt.v1.Tss.team2:type_name -> wt.v1.TssTeam
	5,  // 15: wt.v1.TssTeam.players:type_name -> wt.v1.TssPlayer
	9,  // 16: wt.v1.Player.units:type_name -> wt.v1.Unit
	7,  // 17: wt.v1.Player.elo:type_name -> wt.v1.Elo
	11, // 18: wt.v1.Entity.weapons:type_name -> wt.v1.Weapon
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_replay_proto_init() }
func file_replay_proto_init() {
	if File_replay_proto != nil {
		return
	}
	file_replay_proto_msgTypes[1].OneofWrappers = []any{}
	file_replay_proto_msgTypes[6].OneofWrappers = []any{}
	file_replay_proto_msgTypes[9].OneofWrappers = []any{}
	file_replay_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replay_proto_goTypes,
		DependencyIndexes: file_replay_proto_depIdxs,
		MessageInfos:      file_replay_proto_msgTypes,
	}.Build()
	File_replay_proto = out.File
	file_replay_proto_goTypes = nil
	file_replay_proto_depIdxs = nil
}
